<?php
$arUrlRewrite = [
    [
        'CONDITION' => '#^/payments-and-transfers/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/payments-and-transfers/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/loans/restructuring/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/loans/restructuring/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/mortgage/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/mortgage/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/deposits/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/deposits/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/loans/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/loans/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/cards/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/cards/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/bonus-programs/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/bonus-programs/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/for-corporate-clients/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/for-corporate-clients/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/services/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/services/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/special-offers/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/special-offers/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/support/products_services/#',
        'RULE' => '',
        'ID' => 'bitrix:catalog',
        'PATH' => '/support/products_services/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/support/very_important_information/#',
        'RULE' => '',
        'ID' => 'bitrix:catalog',
        'PATH' => '/support/very_important_information/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/support/announcements_for_clients/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/support/announcements_for_clients/index.php',
    ],
    [
        'CONDITION' => '#^/about/press-center/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/about/press-center/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/about/career/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/about/career/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/about/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/about/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/financial-institutions/#',
        'RULE' => '',
        'ID' => 'bitrix:catalog',
        'PATH' => '/financial-institutions/index.php',
        'SORT' => 100,
    ],

];
