<?php
$arUrlRewrite = [
    [
        'CONDITION' => '#^/for-corporate-clients/mery-gospodderzhki/[a-z-]+/[a-z-]+/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/for-corporate-clients/financing_measures/detail.php',
        'SORT' => 1,
    ],
    [
        'CONDITION' => '#^/for-corporate-clients/mery-gospodderzhki/[a-z-]+/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/for-corporate-clients/financing_measures/section.php',
        'SORT' => 2,
    ],
    [
        'CONDITION' => '#^/for-corporate-clients/customer-announcements/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/for-corporate-clients/customer-announcements/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/support/very_important_information/#',
        'RULE' => '',
        'ID' => 'bitrix:catalog',
        'PATH' => '/support/very_important_information/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/support/announcements_for_clients/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/support/announcements_for_clients/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/support/questions_and_answers/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/support/questions_and_answers/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/support/products_services/#',
        'RULE' => '',
        'ID' => 'bitrix:catalog',
        'PATH' => '/support/products_services/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/payments-and-transfers/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/payments-and-transfers/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/financial-institutions/#',
        'RULE' => '',
        'ID' => 'bitrix:catalog',
        'PATH' => '/financial-institutions/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/for-corporate-clients/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/for-corporate-clients/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/loans/restructuring/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/loans/restructuring/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/about/press-center/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/about/press-center/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/about/purchases/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/about/purchases/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/bonus-programs/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/bonus-programs/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/special-offers/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/special-offers/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/about/career/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/about/career/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/mortgage/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/mortgage/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/deposits/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/deposits/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/services/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/services/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/cards/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/cards/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/about/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/about/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/loans/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/loans/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/msb/#',
        'RULE' => '',
        'ID' => 'bitrix:catalog',
        'PATH' => '/msb/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/map/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/map/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/en/about/#',
        'RULE' => '',
        'ID' => '',
        'PATH' => '/en/about/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/en/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/en/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/private-banking/services/#',
        'RULE' => '',
        'ID' => 'bitrix:news',
        'PATH' => '/private-banking/services/index.php',
        'SORT' => 100,
    ],
    [
        'CONDITION' => '#^/documents/(.+)#',
        'RULE' => 'path=$1',
        'ID' => '',
        'PATH' => '/documents/index.php',
        'SORT' => 100,
    ],
];
