variables:
  AUTODEPLOY_BASE_DOMAIN: s1.main.novikombank.z55.dev.dalee.ru
  GIT_DEPTH: 20

##
# Autodeploy
#
.autodeploy:
  variables:
    GIT_STRATEGY: fetch
    GIT_CHECKOUT: "false"
  stage: deploy
  tags:
    - autodeploy
  before_script:
    - git fetch --prune origin "+refs/heads/master:refs/remotes/origin/master" --depth="$GIT_DEPTH"
    - git remote prune origin
    - echo "Auto-deploing $CI_COMMIT_REF_NAME branch host"
  script:
    - php /app/autodeploy "$CI_COMMIT_REF_NAME" "$CI_PROJECT_DIR"
  environment:
    name: autodeploy/$CI_COMMIT_REF_NAME
    url: http://$CI_COMMIT_REF_SLUG.$AUTODEPLOY_BASE_DOMAIN
    on_stop: "deploy:autodeploy:stop"

deploy:autodeploy:branches:
  extends: .autodeploy
  only:
    - branches
  except:
    - master
    - production
    - /^cherry-pick/
    - /^nodev-/
    - /^revert-/

deploy:autodeploy:trunk:
  extends: .autodeploy
  before_script:
    - echo "Auto-deploing master branch host (trunk)"
  environment:
    url: http://trunk.$AUTODEPLOY_BASE_DOMAIN
  only:
    - master

deploy:autodeploy:stop:
  before_script:
    - git init .
    - rm -f .git/index.lock .git/shallow.lock .git/HEAD.lock .git/hooks/post-checkout
    - git remote set-url origin $CI_REPOSITORY_URL 2>/dev/null || git remote add origin $CI_REPOSITORY_URL
    - git fetch --prune origin "+refs/heads/master:refs/remotes/origin/master" --depth="$GIT_DEPTH"
    - git remote prune origin
    - echo "Removing $CI_COMMIT_REF_NAME branch host"
  script:
    - php /app/autodeploy "$CI_COMMIT_REF_NAME" "$CI_PROJECT_DIR" delete
  extends: .autodeploy
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    action: stop
  only:
    - branches
  except:
    - production

##
# Deploy to production
#
#.base_deploy:
#  stage: deploy
#  image: dalee/php-deployer
#  tags:
#    - docker_dalee
#  before_script:
#    - mkdir -p ~/.ssh && chmod 700 ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
#    - eval $(ssh-agent -s)
#    - chmod 600 $SSH_PRIVATE_DEPLOY_KEY
#    - ssh-add $SSH_PRIVATE_DEPLOY_KEY
#  script:
#    - dep deploy $CI_ENVIRONMENT_NAME -o branch=$CI_COMMIT_REF_NAME
#
#deploy:production:
#  extends: .base_deploy
#  environment:
#    name: production
#    url: https://novikombank.ru/
#  only:
#    - production
