<?php

use Bitrix\Main\Page\Asset;

$APPLICATION->SetTitle('Бонусные программы');
$asset = Asset::getInstance();
$asset->addJs('/frontend/dist/js/calculator-bonus.js');
?>
<?$APPLICATION->IncludeComponent(
    "bitrix:news",
    "bonus_programs",
    [
        "ADD_ELEMENT_CHAIN" => "Y",
        "ADD_SECTIONS_CHAIN" => "N",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "BROWSER_TITLE" => "-",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "36000000",
        "CACHE_TYPE" => "A",
        "CHECK_DATES" => "Y",
        "DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
        "DETAIL_DISPLAY_BOTTOM_PAGER" => "N",
        "DETAIL_DISPLAY_TOP_PAGER" => "N",
        "DETAIL_FIELD_CODE" => ["", ""],
        "DETAIL_PAGER_SHOW_ALL" => "N",
        "DETAIL_PAGER_TEMPLATE" => "",
        "DETAIL_PAGER_TITLE" => "Страница",
        "DETAIL_PROPERTY_CODE" => [
            "ICON",
            "BANNER_STYLE",
            "BENEFITS_COL",
            "BENEFITS_HEADING",
            "BENEFITS",
            "CASHBACK_CATEGORIES",
            "CASHBACK_CATEGORIES_HEADER",
            "SHOW_BONUSES_CALC",
            "BENEFITS_INFO_BOX",
            "TABS_HEADING",
            "TABS",
            "INSTRUCTION_1_HEADING",
            "INSTRUCTION_1",
            "INSTRUCTION_1_COLS",
            "INSTRUCTION_2_HEADING",
            "INSTRUCTION_2",
            "INSTRUCTION_2_COLS",
            "INSTRUCTION_3_HEADING",
            "INSTRUCTION_3",
            "INSTRUCTION_3_COLS",
            "INFO_BOX",
            "INFO_BOX_HEADER",
            "BONUS_BENEFITS",
            "BONUS_BENEFITS_HEADING",
            "BONUS_TABS",
            "BONUS_TABS_HEADING",
            "BONUS_HEADER_TEMPLATE",
            "BONUS_HEADER_IMAGE",
            "BONUS_HEADER_BACKGROUND",
            "BUTTON_SHOW",
            "BUTTON_TEXT",
            "BUTTON_LINK",
        ],
        "DETAIL_SET_CANONICAL_URL" => "N",
        "DISPLAY_BOTTOM_PAGER" => "N",
        "DISPLAY_DATE" => "N",
        "DISPLAY_NAME" => "Y",
        "DISPLAY_PICTURE" => "N",
        "DISPLAY_PREVIEW_TEXT" => "N",
        "DISPLAY_TOP_PAGER" => "N",
        "FILE_404" => "",
        "HIDE_LINK_WHEN_NO_DETAIL" => "N",
        "IBLOCK_ID" => $iblockId,
        "IBLOCK_TYPE" => "additional",
        "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
        "LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
        "LIST_FIELD_CODE" => ["", ""],
        "LIST_PROPERTY_CODE" => ["", ""],
        "MESSAGE_404" => "",
        "META_DESCRIPTION" => "-",
        "META_KEYWORDS" => "-",
        "NEWS_COUNT" => "20",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_TEMPLATE" => ".default",
        "PAGER_TITLE" => "Новости",
        "PREVIEW_TRUNCATE_LEN" => "",
        "SEF_FOLDER" => "/cards/",
        "SEF_MODE" => "Y",
        "SEF_URL_TEMPLATES" => [
            "detail" => "#ELEMENT_CODE#/",
            "news" => "",
            "section" => ""
        ],
        "SET_LAST_MODIFIED" => "N",
        "SET_STATUS_404" => "Y",
        "SET_TITLE" => "Y",
        "SHOW_404" => "Y",
        "SORT_BY1" => "ACTIVE_FROM",
        "SORT_BY2" => "SORT",
        "SORT_ORDER1" => "DESC",
        "SORT_ORDER2" => "ASC",
        "STRICT_SECTION_CHECK" => "Y",
        "USE_CATEGORIES" => "N",
        "USE_FILTER" => "N",
        "USE_PERMISSIONS" => "N",
        "USE_RATING" => "N",
        "USE_RSS" => "N",
        "USE_SEARCH" => "N",
        "USE_SHARE" => "N"
    ]
);?>
